default: &default
  adapter: <%= ENV['PRODUCTION_DATABASE_ADAPTER'] %>
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: <%= ENV['PRODUCTION_DATABASE_DATABASE'] %>

test:
  <<: *default
  database: kummerkasten_test
production:
  <<: *default
  host: <%= ENV['PRODUCTION_DATABASE_HOST'] %>
  port: <%= ENV['PRODUCTION_DATABASE_PORT'] %>
  database: <%= ENV['PRODUCTION_DATABASE_DATABASE'] %>
  username: <%= ENV['PRODUCTION_DATABASE_USERNAME'] %>
  password: <%= ENV['PRODUCTION_DATABASE_PASSWORD'] %>
