query($organization: ID!) {
  organization(id: $organization) {
    title
    description
    id
    meetings {
      id
      title
      description
      organization {
        id
      }
    }
    tops {
      id
      title
      description
      organization {
        id
      }
    }
  }
}

